<script lang="ts">
  import { onMount } from 'svelte'; import SettingsHeader from '$lib/components/SettingsHeader.svelte'; import UiButton from '$lib/components/ui/UiButton.svelte'; import { api } from '$lib/api'; import type { ScaleMeasurement } from '$lib/types';
  let measurements: ScaleMeasurement[] = []; let loading = true; let error = '';
  async function load() { loading = true; error = ''; try { measurements = (await api.getScaleMeasurements()) ?? []; } catch { error = 'Messungen konnten nicht geladen werden.'; } finally { loading = false; } }
  async function remove(item: ScaleMeasurement) { if (!confirm(`Messung vom ${formatDate(item.measured_at)} aus deiner Ansicht entfernen?`)) return; const result = await api.removeScaleMeasurement(item.id); if (result) measurements = measurements.filter((current) => current.id !== item.id); else error = 'Die Messung konnte nicht entfernt werden.'; }
  function formatDate(value: string) { return new Date(value).toLocaleString('de-DE', { dateStyle: 'medium', timeStyle: 'short' }); } onMount(load);
</script>
<svelte:head><title>FitTrack – Waagenmessungen</title></svelte:head>
<div class="page"><SettingsHeader title="Waagenmessungen" subtitle="Nur Messungen, die deinem Konto zugeordnet sind" /><section class="section-card" aria-busy={loading}><div class="section-header"><span>Messverlauf</span><UiButton onclick={load} disabled={loading}>Aktualisieren</UiButton></div>{#if error}<p class="message error" role="alert">{error}</p>{/if}{#if loading}<p class="message" role="status">Messungen werden geladen…</p>{:else if measurements.length}<ul>{#each measurements as item (item.id)}<li><div><strong>{Number(item.weight_kg).toFixed(1)} kg</strong><span>{formatDate(item.measured_at)} · automatisch zugeordnet</span></div><UiButton onclick={() => remove(item)}>Entfernen</UiButton></li>{/each}</ul>{:else}<p class="message">Noch keine Waagenmessung vorhanden. Manuelle Gewichtseinträge bleiben in der Tagesansicht verfügbar.</p>{/if}</section><p class="footnote">Entfernte Messungen werden nicht gelöscht oder an ein anderes Konto übertragen.</p></div>
<style>.page{display:grid;gap:var(--space-3);padding-top:var(--space-2)}ul{list-style:none}li{display:flex;align-items:center;justify-content:space-between;gap:var(--space-3);padding:var(--space-3) var(--space-4);border-top:1px solid var(--border-subtle)}li div{display:grid;gap:2px}li strong{font-size:16px}li span,.message,.footnote{color:var(--text-tertiary);font-size:12px;line-height:1.45}.message{padding:var(--space-4)}.error{color:var(--status-danger)}.footnote{padding:0 var(--space-2)}</style>
