<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  import type { Contact, ContactInvitation, ContactOutgoingInvitation, ContactSearchResult, SpaceInvitation } from '$lib/types';

  let contacts: Contact[] = []; let invitations: ContactInvitation[] = []; let outgoing: ContactOutgoingInvitation[] = []; let workspaceInvitations: SpaceInvitation[] = [];
  let query = ''; let results: ContactSearchResult[] = []; let message = ''; let loading = true; let searching = false; let searchGeneration = 0;
  async function load() { loading = true; [contacts, invitations, outgoing, workspaceInvitations] = await Promise.all([api.getContacts(), api.getContactInvitations(), api.getOutgoingContactInvitations(), api.getSpaceInvitations()]); loading = false; }
  async function search() { const generation = ++searchGeneration; const value = query.trim(); if (value.replace('@', '').length < 2) { results = []; searching = false; return; } searching = true; try { const found = await api.searchContacts(value); if (generation === searchGeneration) results = found; } finally { if (generation === searchGeneration) searching = false; } }
  async function invite(alias: string) { if (await api.inviteContact(alias)) { message = `Anfrage an @${alias} wurde gesendet.`; query = ''; results = []; await load(); } else message = 'Kontaktanfrage konnte nicht gesendet werden.'; }
  async function accept(id: string) { if (await api.acceptContactInvitation(id)) { message = 'Kontakt hinzugefügt.'; await load(); } }
  async function decline(id: string) { if (await api.declineContactInvitation(id)) { message = 'Anfrage abgelehnt.'; await load(); } }
  async function acceptWorkspace(id: string) { if (await api.acceptSpaceInvitation(id)) { message = 'Workspace hinzugefügt.'; await load(); } }
  async function declineWorkspace(id: string) { if (await api.declineSpaceInvitation(id)) { message = 'Workspace-Anfrage abgelehnt.'; await load(); } }
  async function remove(id: string) { if (confirm('Kontakt wirklich entfernen?') && await api.removeContact(id)) { message = 'Kontakt entfernt.'; await load(); } }
  onMount(load);
</script>

<svelte:head><title>Cronicl – Kontakte</title></svelte:head>
<div class="page"><header><p>KONTAKTE</p><h1>Deine Kontakte</h1><span>Finde Personen über ihren @alias – E-Mail-Adressen bleiben privat.</span></header>
  <section class="surface"><label for="contact-search">Kontakt suchen</label><div class="search"><input id="contact-search" bind:value={query} oninput={search} placeholder="@alias eingeben" autocomplete="off" /><span aria-live="polite">{searching ? 'Sucht…' : ''}</span></div>{#if results.length}<ul class="results" aria-label="Gefundene Kontakte">{#each results as result (result.alias)}<li><span><strong>{result.display_name}</strong><small>@{result.alias}</small></span><button class="primary" aria-label={`Kontaktanfrage an ${result.display_name} senden`} onclick={() => invite(result.alias)}>Anfragen</button></li>{/each}</ul>{:else if query.replace('@', '').length >= 2 && !searching}<p class="hint" role="status">Kein passender Alias gefunden.</p>{/if}</section>
  {#if workspaceInvitations.length}<section class="surface"><h2>Workspace-Anfragen</h2>{#each workspaceInvitations as item (item.id)}<div class="row"><span>{item.space_name}{#if item.invited_by_display_name} · von {item.invited_by_display_name}{/if}</span><div><button onclick={() => acceptWorkspace(item.id)}>Annehmen</button><button onclick={() => declineWorkspace(item.id)}>Ablehnen</button></div></div>{/each}</section>{/if}
  {#if invitations.length}<section class="surface"><h2>Eingegangene Anfragen</h2>{#each invitations as item (item.id)}<div class="row"><span>{item.invited_by_display_name} · @{item.invited_by_alias}</span><div><button onclick={() => accept(item.id)}>Annehmen</button><button onclick={() => decline(item.id)}>Ablehnen</button></div></div>{/each}</section>{/if}
  {#if outgoing.length}<section class="surface"><h2>Ausstehende Anfragen</h2>{#each outgoing as item (item.id)}<div class="row"><span>{item.invited_display_name} · @{item.invited_alias}</span><small>Wartet auf Annahme</small></div>{/each}</section>{/if}
  <section class="surface"><h2>Übersicht</h2>{#if loading}<p>Lade Kontakte…</p>{:else if contacts.length}<ul class="results">{#each contacts as contact (contact.id)}<li><span><strong>{contact.display_name}</strong><small>@{contact.alias}</small></span><button class="remove" onclick={() => remove(contact.id)}>Entfernen</button></li>{/each}</ul>{:else}<p>Noch keine Kontakte. Kontakte geben keinen Zugriff auf private Daten oder Workspaces.</p>{/if}</section>{#if message}<p class="message" role="status">{message}</p>{/if}</div>

<style>.page{display:grid;gap:12px;padding:18px 4px}.page header p{font-size:11px;font-weight:750;letter-spacing:.08em;color:var(--action-primary)}h1{margin:3px 0;font-size:25px}.page header span,.hint,small{color:var(--text-secondary);font-size:13px}.surface{padding:15px;border:1px solid var(--border-subtle);border-radius:var(--radius-card);background:var(--surface-default)}h2{margin:0 0 10px;font-size:16px}.search{display:flex;gap:8px;align-items:center}.search input{flex:1}.results{list-style:none;margin:10px 0 0;padding:0}.results li,.row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px 0;border-top:1px solid var(--border-subtle)}.results span{display:grid;gap:2px}.row div{display:flex;gap:6px}button{min-height:var(--control-min)}.primary{background:var(--action-primary);color:white}.remove{color:var(--status-danger)}.message{margin:0;color:var(--status-success)}</style>
