"""Cronicl baseline

Revision ID: 7095ad546555
Revises: 
Create Date: 2026-09-01 19:19:28.122575

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7095ad546555'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('google_subject', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_subject')
    )
    op.create_table('registered_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('credential_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('account_weight_ranges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('baseline_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('lower_offset_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('upper_offset_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('baseline_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('body_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('calculation_sex', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', name='uq_body_profiles_account')
    )
    op.create_index(op.f('ix_body_profiles_account_id'), 'body_profiles', ['account_id'], unique=False)
    op.create_table('day_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_source', sa.Text(), nullable=True),
    sa.Column('bmi', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('sleep_deep_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('sleep_rem_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('sleep_light_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('sleep_awake_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('sleep_efficiency', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('cardio_minutes', sa.Integer(), nullable=True),
    sa.Column('training_type', sa.Text(), nullable=True),
    sa.Column('training_done', sa.Boolean(), nullable=False),
    sa.Column('rotation_slot', sa.Integer(), nullable=True),
    sa.Column('steps_done', sa.Boolean(), nullable=False),
    sa.Column('steps_confirmed', sa.Boolean(), nullable=False),
    sa.Column('steps_source', sa.Text(), nullable=True),
    sa.Column('sleep_done', sa.Boolean(), nullable=False),
    sa.Column('creatine_done', sa.Boolean(), nullable=False),
    sa.Column('cardio_done', sa.Boolean(), nullable=False),
    sa.Column('belly_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', name='uq_day_entries_account_date')
    )
    op.create_index(op.f('ix_day_entries_account_id'), 'day_entries', ['account_id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('training_type', sa.Text(), nullable=False),
    sa.Column('exercise_name', sa.Text(), nullable=False),
    sa.Column('target_sets', sa.Text(), nullable=False),
    sa.Column('target_reps_low', sa.Integer(), nullable=True),
    sa.Column('target_reps_high', sa.Integer(), nullable=True),
    sa.Column('base_reps_low', sa.Integer(), nullable=True),
    sa.Column('base_reps_high', sa.Integer(), nullable=True),
    sa.Column('target_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('progression_strategy', sa.Text(), nullable=False),
    sa.Column('progression_increment_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_topset', sa.Boolean(), nullable=False),
    sa.Column('top_set_count', sa.Integer(), nullable=False),
    sa.Column('backoff_set_count', sa.Integer(), nullable=False),
    sa.Column('backoff_reps_low', sa.Integer(), nullable=True),
    sa.Column('backoff_reps_high', sa.Integer(), nullable=True),
    sa.Column('backoff_weight_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_rir', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'training_type', 'exercise_name', name='uq_exercises_account_type_name')
    )
    op.create_index(op.f('ix_exercises_account_id'), 'exercises', ['account_id'], unique=False)
    op.create_table('foods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Text(), nullable=False),
    sa.Column('kcal_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('protein_g_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('carbs_g_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fat_g_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fiber_g_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sugar_g_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('free_sugar_g_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('saturated_fat_g_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sodium_mg_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('potassium_mg_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('calcium_mg_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('magnesium_mg_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('iron_mg_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('zinc_mg_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('vitamin_a_ug_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('vitamin_c_mg_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('vitamin_d_ug_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('vitamin_b12_ug_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('folate_ug_per_100g', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_foods_account_name')
    )
    op.create_index(op.f('ix_foods_account_id'), 'foods', ['account_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'key', name='uq_goals_account_key')
    )
    op.create_index(op.f('ix_goals_account_id'), 'goals', ['account_id'], unique=False)
    op.create_table('google_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_tokens_account_id'), 'google_tokens', ['account_id'], unique=False)
    op.create_table('meal_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_meal_categories_account_name')
    )
    op.create_index(op.f('ix_meal_categories_account_id'), 'meal_categories', ['account_id'], unique=False)
    op.create_table('meal_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_account_id'), 'meal_plans', ['account_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('servings', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('instructions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nutrition_per_serving', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_recipes_account_name')
    )
    op.create_index(op.f('ix_recipes_account_id'), 'recipes', ['account_id'], unique=False)
    op.create_table('scale_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('device_event_id', sa.Text(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('impedance_ohm', sa.Integer(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('assignment_method', sa.Text(), nullable=False),
    sa.Column('assignment_confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('assignment_reason', sa.Text(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bmi', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('profile_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'device_event_id', name='uq_scale_measurements_device_event')
    )
    op.create_index(op.f('ix_scale_measurements_account_id'), 'scale_measurements', ['account_id'], unique=False)
    op.create_table('sync_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('client_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('synced', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_log_account_id'), 'sync_log', ['account_id'], unique=False)
    op.create_table('todo_routines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('weekdays', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('due_time', sa.Time(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_routines_account_id'), 'todo_routines', ['account_id'], unique=False)
    op.create_table('todos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_time', sa.Time(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('place_id', sa.Text(), nullable=True),
    sa.Column('place_name', sa.Text(), nullable=True),
    sa.Column('place_address', sa.Text(), nullable=True),
    sa.Column('travel_mode', sa.Text(), nullable=True),
    sa.Column('travel_buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('travel_monitoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('travel_last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('travel_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('travel_depart_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_account_id'), 'todos', ['account_id'], unique=False)
    op.create_table('training_rotation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('training_type', sa.Text(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('frequency_weeks', sa.Integer(), nullable=False),
    sa.Column('week_offset', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slot', name='uq_training_rotation_account_slot')
    )
    op.create_index(op.f('ix_training_rotation_account_id'), 'training_rotation', ['account_id'], unique=False)
    op.create_table('training_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('training_type', sa.Text(), nullable=False),
    sa.Column('exercise_name', sa.Text(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.Text(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', 'exercise_name', 'set_number', name='uq_training_set_account_date_ex_set')
    )
    op.create_index(op.f('ix_training_sets_account_id'), 'training_sets', ['account_id'], unique=False)
    op.create_table('training_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_type', sa.Text(), nullable=False),
    sa.Column('cardio_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_training_units_account_name')
    )
    op.create_index(op.f('ix_training_units_account_id'), 'training_units', ['account_id'], unique=False)
    op.create_table('exercise_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('training_type', sa.Text(), nullable=False),
    sa.Column('exercise_name', sa.Text(), nullable=False),
    sa.Column('topset_reps', sa.Integer(), nullable=True),
    sa.Column('topset_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('topset_rir', sa.Integer(), nullable=True),
    sa.Column('all_sets_reps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_volume_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('progression_action', sa.Text(), nullable=False),
    sa.Column('prev_target_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('prev_target_reps_low', sa.Integer(), nullable=True),
    sa.Column('new_target_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('new_target_reps_low', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'exercise_id', 'date', name='uq_exercise_progress_account_exercise_date')
    )
    op.create_index(op.f('ix_exercise_progress_account_id'), 'exercise_progress', ['account_id'], unique=False)
    op.create_table('meal_category_recipe_presets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['meal_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'category_id', 'rank', name='uq_meal_category_recipe_preset_rank'),
    sa.UniqueConstraint('account_id', 'category_id', 'recipe_id', name='uq_meal_category_recipe_preset_recipe')
    )
    op.create_index(op.f('ix_meal_category_recipe_presets_account_id'), 'meal_category_recipe_presets', ['account_id'], unique=False)
    op.create_table('meal_plan_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_plan_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('planned_time', sa.Time(), nullable=True),
    sa.Column('weekdays', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('portion', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['meal_categories.id'], ),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_items_account_id'), 'meal_plan_items', ['account_id'], unique=False)
    op.create_table('meal_plan_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_plan_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('items_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meal_plan_id', 'version', name='uq_meal_plan_versions_plan_version')
    )
    op.create_index(op.f('ix_meal_plan_versions_account_id'), 'meal_plan_versions', ['account_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('nested_recipe_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['nested_recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'sort_order', name='uq_recipe_ingredients_order')
    )
    op.create_index(op.f('ix_recipe_ingredients_account_id'), 'recipe_ingredients', ['account_id'], unique=False)
    op.create_table('meal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('meal_plan_id', sa.UUID(), nullable=True),
    sa.Column('meal_plan_item_id', sa.UUID(), nullable=True),
    sa.Column('meal_plan_version', sa.Integer(), nullable=True),
    sa.Column('nutrition_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['meal_categories.id'], ),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ),
    sa.ForeignKeyConstraint(['meal_plan_item_id'], ['meal_plan_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', 'meal_plan_id', 'meal_plan_item_id', name='uq_meal_entries_plan_instance')
    )
    op.create_index(op.f('ix_meal_entries_account_id'), 'meal_entries', ['account_id'], unique=False)
    op.create_table('meal_entry_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_entry_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('nutrition_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['meal_entry_id'], ['meal_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_entry_items_account_id'), 'meal_entry_items', ['account_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_entry_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['meal_entry_id'], ['meal_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_account_id'), 'photos', ['account_id'], unique=False)
    op.create_table('meal_photo_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('meal_entry_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.Text(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['meal_entry_id'], ['meal_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id', name='uq_meal_photo_analyses_photo')
    )
    op.create_index(op.f('ix_meal_photo_analyses_account_id'), 'meal_photo_analyses', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_photo_analyses_account_id'), table_name='meal_photo_analyses')
    op.drop_table('meal_photo_analyses')
    op.drop_index(op.f('ix_photos_account_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_meal_entry_items_account_id'), table_name='meal_entry_items')
    op.drop_table('meal_entry_items')
    op.drop_index(op.f('ix_meal_entries_account_id'), table_name='meal_entries')
    op.drop_table('meal_entries')
    op.drop_index(op.f('ix_recipe_ingredients_account_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_meal_plan_versions_account_id'), table_name='meal_plan_versions')
    op.drop_table('meal_plan_versions')
    op.drop_index(op.f('ix_meal_plan_items_account_id'), table_name='meal_plan_items')
    op.drop_table('meal_plan_items')
    op.drop_index(op.f('ix_meal_category_recipe_presets_account_id'), table_name='meal_category_recipe_presets')
    op.drop_table('meal_category_recipe_presets')
    op.drop_index(op.f('ix_exercise_progress_account_id'), table_name='exercise_progress')
    op.drop_table('exercise_progress')
    op.drop_index(op.f('ix_training_units_account_id'), table_name='training_units')
    op.drop_table('training_units')
    op.drop_index(op.f('ix_training_sets_account_id'), table_name='training_sets')
    op.drop_table('training_sets')
    op.drop_index(op.f('ix_training_rotation_account_id'), table_name='training_rotation')
    op.drop_table('training_rotation')
    op.drop_index(op.f('ix_todos_account_id'), table_name='todos')
    op.drop_table('todos')
    op.drop_index(op.f('ix_todo_routines_account_id'), table_name='todo_routines')
    op.drop_table('todo_routines')
    op.drop_index(op.f('ix_sync_log_account_id'), table_name='sync_log')
    op.drop_table('sync_log')
    op.drop_index(op.f('ix_scale_measurements_account_id'), table_name='scale_measurements')
    op.drop_table('scale_measurements')
    op.drop_index(op.f('ix_recipes_account_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_meal_plans_account_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_meal_categories_account_id'), table_name='meal_categories')
    op.drop_table('meal_categories')
    op.drop_index(op.f('ix_google_tokens_account_id'), table_name='google_tokens')
    op.drop_table('google_tokens')
    op.drop_index(op.f('ix_goals_account_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_foods_account_id'), table_name='foods')
    op.drop_table('foods')
    op.drop_index(op.f('ix_exercises_account_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_day_entries_account_id'), table_name='day_entries')
    op.drop_table('day_entries')
    op.drop_index(op.f('ix_body_profiles_account_id'), table_name='body_profiles')
    op.drop_table('body_profiles')
    op.drop_table('account_weight_ranges')
    op.drop_table('registered_devices')
    op.drop_table('accounts')
    # ### end Alembic commands ###