<script lang="ts">
  import { createEventDispatcher, tick } from 'svelte';
  import { api } from '$lib/api';
  export let open = false;
  export let date: string;
  export let initialText = '';
  const dispatch = createEventDispatcher<{ close: void }>();
  let dialog: HTMLDialogElement; let text = ''; let answer = ''; let loading = false; let error = ''; let opener: HTMLElement | null = null;
  $: if (open && dialog && !dialog.open) { opener = document.activeElement instanceof HTMLElement ? document.activeElement : null; text = initialText; answer = ''; error = ''; dialog.showModal(); void tick().then(() => dialog.querySelector<HTMLTextAreaElement>('textarea')?.focus()); }
  $: if (!open && dialog?.open) dialog.close();
  function close() { dispatch('close'); }
  async function ask() { if (!text.trim() || loading) return; loading = true; error = ''; try { answer = await api.askAssistant(text.trim(), date) ?? ''; if (!answer) throw new Error(); } catch { error = 'Die KI ist gerade nicht erreichbar. Bitte versuche es später erneut.'; } finally { loading = false; } }
</script>
<dialog bind:this={dialog} class="chat" aria-labelledby="assistant-title" oncancel={(e) => { e.preventDefault(); close(); }} onclose={() => opener?.focus()}><form onsubmit={(e) => { e.preventDefault(); ask(); }}><header><div><p>KI-ASSISTENT</p><h2 id="assistant-title">Wie kann ich helfen?</h2></div><button type="button" aria-label="KI-Chat schließen" onclick={close}>×</button></header><label for="assistant-question">Deine Frage<textarea id="assistant-question" bind:value={text} placeholder="z. B. Ich möchte meinen Ernährungsplan anpassen."></textarea></label><div class="actions"><button type="button" onclick={close}>Schließen</button><button class="primary" disabled={!text.trim() || loading}>{loading ? 'Denke nach…' : 'Fragen'}</button></div>{#if answer}<section aria-live="polite"><p>ANTWORT</p>{answer}</section>{/if}{#if error}<p class="error" role="alert">{error}</p>{/if}</form></dialog>
<style>.chat{width:min(calc(100% - 24px),520px);max-height:86dvh;margin:auto;padding:0;border:1px solid var(--border-default);border-radius:var(--radius-modal);background:var(--surface-default);color:var(--text-primary);box-shadow:var(--shadow-modal)}.chat::backdrop{background:var(--overlay-backdrop)}form{display:grid;gap:var(--space-3);padding:var(--space-4)}header{display:flex;justify-content:space-between}header p,section p{margin:0 0 3px;color:var(--text-tertiary);font-size:11px;font-weight:700}h2{margin:0;font-size:18px}label{display:grid;gap:5px;font-size:12px;color:var(--text-secondary)}textarea{min-height:96px;padding:9px;border:1px solid var(--border-default);border-radius:var(--radius-control);background:var(--surface-raised);color:var(--text-primary);font:inherit}button{min-height:var(--control-min);padding:8px 12px;border:1px solid var(--border-default);border-radius:var(--radius-control);background:var(--surface-raised);color:var(--text-primary);cursor:pointer}.primary{border:0;background:var(--action-primary);color:var(--text-on-accent)}.actions{display:flex;justify-content:flex-end;gap:var(--space-2)}section{white-space:pre-wrap;line-height:1.5;padding:var(--space-3);background:var(--surface-raised);border-radius:var(--radius-control)}.error{margin:0;color:var(--status-danger)}button:focus-visible,textarea:focus-visible{outline:2px solid var(--status-info);outline-offset:2px}</style>
