<script lang="ts">
  import { createEventDispatcher, tick } from 'svelte';
  import { api } from '$lib/api';
  import type { ShoppingList, ShoppingMealPreview } from '$lib/types';
  export let open = false;
  export let startDate = '';
  const dispatch = createEventDispatcher<{ close: void; imported: ShoppingList }>();
  let dialog: HTMLDialogElement; let days = 7; let preview: ShoppingMealPreview | null = null; let loading = false; let saving = false; let error = ''; let request = 0;
  function endDate() { const date = new Date(`${startDate}T00:00:00`); date.setDate(date.getDate() + days - 1); return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; }
  async function load() { if (!open || !startDate) return; const current = ++request; loading = true; error = ''; const result = await api.getShoppingMealPreview(startDate, endDate()); if (current === request) { preview = result; loading = false; if (!result) error = 'Die Mahlzeitenvorschau ist gerade nicht verfügbar.'; } }
  $: if (open && dialog && !dialog.open) { dialog.showModal(); tick().then(load); }
  $: if (!open && dialog?.open) dialog.close();
  $: if (open && startDate && dialog?.open) load();
  async function confirm() { if (saving || !preview) return; saving = true; const result = await api.importShoppingMealPlan(startDate, endDate()); saving = false; if (result) { dispatch('imported', result); dispatch('close'); } else error = 'Die Zutaten konnten nicht übernommen werden.'; }
</script>
<dialog bind:this={dialog} class="import" aria-labelledby="shopping-import-title" oncancel={(event) => { event.preventDefault(); dispatch('close'); }}><form onsubmit={(event) => { event.preventDefault(); confirm(); }}><header><div><p>MAHLZEITENPLAN</p><h2 id="shopping-import-title">Zutaten übernehmen</h2></div><button type="button" onclick={() => dispatch('close')} aria-label="Übernahme schließen">×</button></header><label>Startdatum<input type="date" bind:value={startDate}/></label><label>Zeitraum<select bind:value={days}>{#each Array.from({length:14}, (_, index) => index + 1) as day}<option value={day}>{day} {day === 1 ? 'Tag' : 'Tage'}</option>{/each}</select></label>{#if loading}<p class="hint">Prüfe geplante Mahlzeiten…</p>{:else if preview}<p class="hint">{preview.plan_name ?? 'Kein aktiver Plan'} · {preview.items.length} Zutaten</p><ul>{#each preview.items as item}<li>{item.title}{#if item.quantity != null}<span>{Number(item.quantity.toFixed(3))} {item.unit}</span>{/if}{#if item.needs_review}<em>prüfen</em>{/if}</li>{:else}<li>Keine Rezeptzutaten im gewählten Zeitraum.</li>{/each}</ul>{/if}{#if error}<p class="error" role="alert">{error}</p>{/if}<footer><button type="button" onclick={() => dispatch('close')}>Abbrechen</button><button class="primary" type="submit" disabled={!preview || saving || preview.items.length === 0}>{saving ? 'Übernehme…' : 'Bestätigen'}</button></footer></form></dialog>
<style>.import{width:min(calc(100% - 24px),460px);margin:auto;padding:0;border:1px solid var(--border-default);border-radius:var(--radius-modal);background:var(--surface-default);color:var(--text-primary);box-shadow:var(--shadow-modal)}.import::backdrop{background:var(--overlay-backdrop)}form{display:grid;gap:var(--space-3);padding:var(--space-4)}header{display:flex;justify-content:space-between}header p{margin:0;color:var(--text-tertiary);font-size:11px;font-weight:700;letter-spacing:.06em}h2{margin:3px 0 0;font-size:18px}label{display:grid;gap:5px;color:var(--text-secondary);font-size:12px}input,select{min-height:var(--control-min);padding:8px 10px;border:1px solid var(--border-default);border-radius:var(--radius-control);background:var(--surface-raised);color:var(--text-primary);font:inherit}ul{max-height:200px;overflow:auto;margin:0;padding:0;list-style:none;border:1px solid var(--border-subtle);border-radius:var(--radius-control)}li{display:flex;justify-content:space-between;gap:8px;padding:8px 10px;border-bottom:1px solid var(--border-subtle);font-size:13px}li:last-child{border:0}li span,em,.hint{color:var(--text-tertiary);font-size:11px}.hint{margin:0}.error{margin:0;color:var(--status-danger);font-size:12px}footer{display:flex;justify-content:flex-end;gap:var(--space-2)}button{min-height:var(--control-min);padding:8px 12px;border:1px solid var(--border-default);border-radius:var(--radius-control);background:var(--surface-raised);color:var(--text-primary)}.primary{background:var(--action-primary);border-color:var(--action-primary);color:var(--text-on-accent);font-weight:700}</style>
