<script lang="ts">
  import { createEventDispatcher, tick } from 'svelte';
  import Icon from './Icon.svelte';
  import type { ShoppingItem } from '$lib/types';
  export let item: ShoppingItem | null = null;
  const dispatch = createEventDispatcher<{ close: void; save: { id: string; data: Partial<ShoppingItem> } }>();
  let dialog: HTMLDialogElement; let title = ''; let quantity = ''; let unit = ''; let note = ''; let category = 'other'; let icon = 'shopping'; let opener: HTMLElement | null = null;
  $: if (item && dialog && !dialog.open) { opener = document.activeElement instanceof HTMLElement ? document.activeElement : null; title = item.title; quantity = item.quantity == null ? '' : String(item.quantity); unit = item.unit ?? ''; note = item.note ?? ''; category = item.category_key; icon = item.icon_key; dialog.showModal(); tick().then(() => dialog.querySelector<HTMLInputElement>('#shopping-edit-title')?.focus()); }
  $: if (!item && dialog?.open) dialog.close();
  function close() { dispatch('close'); }
  function save() { if (!item || !title.trim()) return; const parsed = quantity.trim() ? Number(quantity) : null; if (parsed !== null && (!Number.isFinite(parsed) || parsed <= 0)) return; dispatch('save', { id: item.id, data: { title: title.trim(), quantity: parsed, unit: unit.trim() || null, note: note.trim() || null, category_key: category, icon_key: icon } }); close(); }
</script>

<dialog bind:this={dialog} class="editor" aria-labelledby="shopping-editor-title" oncancel={(event) => { event.preventDefault(); close(); }} onclose={() => opener?.focus()}>{#if item}<form onsubmit={(event) => { event.preventDefault(); save(); }}><header><div><p>ARTIKEL</p><h2 id="shopping-editor-title">Einkauf bearbeiten</h2></div><button type="button" onclick={close} aria-label="Bearbeiten schließen"><Icon name="x" size={20}/></button></header><label>Artikel<input id="shopping-edit-title" bind:value={title} required/></label><div class="two"><label>Menge<input type="number" min="0.001" step="0.001" bind:value={quantity}/></label><label>Einheit<input placeholder="z. B. g oder Stück" bind:value={unit}/></label></div><div class="two"><label>Kategorie<select bind:value={category}>{#each [['produce','Obst & Gemüse'],['dairy','Kühlregal'],['bakery','Backwaren'],['pantry','Vorrat'],['frozen','Tiefkühlung'],['beverage','Getränke'],['household','Haushalt'],['other','Sonstiges']] as option}<option value={option[0]}>{option[1]}</option>{/each}</select></label><label>Icon<select bind:value={icon}>{#each ['shopping','produce','dairy','bakery','pantry','frozen','beverage','household'] as option}<option value={option}>{option}</option>{/each}</select></label></div><label>Notiz<input bind:value={note}/></label><footer><button type="button" onclick={close}>Abbrechen</button><button class="primary" type="submit">Speichern</button></footer></form>{/if}</dialog>

<style>.editor { width:min(calc(100% - 24px),460px); margin:auto; padding:0; border:1px solid var(--border-default); border-radius:var(--radius-modal); background:var(--surface-default); color:var(--text-primary); box-shadow:var(--shadow-modal); }.editor::backdrop { background:var(--overlay-backdrop); } form { display:grid; gap:var(--space-3); padding:var(--space-4); } header { display:flex; justify-content:space-between; gap:var(--space-3); } header p { margin:0 0 3px; color:var(--text-tertiary); font-size:11px; font-weight:700; letter-spacing:.06em; } h2 { margin:0; font-size:18px; } label { display:grid; gap:5px; color:var(--text-secondary); font-size:12px; } input,select { width:100%; min-height:var(--control-min); padding:8px 10px; border:1px solid var(--border-default); border-radius:var(--radius-control); background:var(--surface-raised); color:var(--text-primary); font:inherit; } .two { display:grid; grid-template-columns:1fr 1fr; gap:var(--space-2); } header button,footer button { min-height:var(--control-min); padding:8px 12px; border:1px solid var(--border-default); border-radius:var(--radius-control); background:var(--surface-raised); color:var(--text-primary); } footer { display:flex; justify-content:flex-end; gap:var(--space-2); } footer .primary { background:var(--action-primary); border-color:var(--action-primary); color:var(--text-on-accent); font-weight:700; } @media(max-width:420px) { .editor { width:100%; margin:auto 0 0; border-radius:var(--radius-modal) var(--radius-modal) 0 0; } .two { grid-template-columns:1fr; } }</style>
